# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then Rscript -e 'covr::codecov()'; fi
  
r:
#  - oldrel
  - release
  - devel
  
os:
  - linux
  - osx
  
# For some reason statnet.common is not found in the oldrel (I think)
r_github_packages:
  - statnet/statnet.common

