# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then Rscript -e 'covr::codecov()'; fi
  
# For some reason statnet.common is not found in the oldrel (I think)
r_github_packages:
  - statnet/statnet.common
  
brew_packages: libgit2

# We don't want the devel version on OSX
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
